//! C FFI bindings for libduvm.
//!
//! These functions provide a C-compatible API for non-Rust applications.
//! The header file is generated by cbindgen during build.

use crate::pool::Pool;
use duvm_common::page::PAGE_SIZE;
use std::ptr;
use std::sync::OnceLock;

static GLOBAL_POOL: OnceLock<Pool> = OnceLock::new();

fn get_pool() -> Option<&'static Pool> {
    GLOBAL_POOL.get()
}

/// Initialize the duvm library. Must be called before any other duvm function.
/// Returns 0 on success, -1 on error.
#[unsafe(no_mangle)]
pub extern "C" fn duvm_init() -> i32 {
    match Pool::standalone() {
        Ok(pool) => {
            if GLOBAL_POOL.set(pool).is_err() {
                return -1; // already initialized
            }
            0
        }
        Err(_) => -1,
    }
}

/// Store a 4KB page. Returns a handle (u64) on success, or u64::MAX on error.
///
/// # Safety
/// `data` must point to at least 4096 bytes of readable memory.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn duvm_store_page(data: *const u8) -> u64 {
    if data.is_null() {
        return u64::MAX;
    }
    let pool = match get_pool() {
        Some(p) => p,
        None => return u64::MAX,
    };
    let buf: &[u8; PAGE_SIZE] = unsafe { &*(data as *const [u8; PAGE_SIZE]) };
    match pool.store(buf) {
        Ok(handle) => handle.raw(),
        Err(_) => u64::MAX,
    }
}

/// Load a 4KB page by handle. Returns 0 on success, -1 on error.
///
/// # Safety
/// `buf` must point to at least 4096 bytes of writable memory.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn duvm_load_page(handle: u64, buf: *mut u8) -> i32 {
    if buf.is_null() {
        return -1;
    }
    let pool = match get_pool() {
        Some(p) => p,
        None => return -1,
    };
    let page_handle = duvm_common::page::PageHandle::from_raw(handle);
    match pool.load(page_handle) {
        Ok(data) => {
            unsafe {
                ptr::copy_nonoverlapping(data.as_ptr(), buf, PAGE_SIZE);
            }
            0
        }
        Err(_) => -1,
    }
}

/// Free a page by handle. Returns 0 on success, -1 on error.
#[unsafe(no_mangle)]
pub extern "C" fn duvm_free_page(handle: u64) -> i32 {
    let pool = match get_pool() {
        Some(p) => p,
        None => return -1,
    };
    let page_handle = duvm_common::page::PageHandle::from_raw(handle);
    match pool.free(page_handle) {
        Ok(()) => 0,
        Err(_) => -1,
    }
}

/// Get total capacity in pages.
#[unsafe(no_mangle)]
pub extern "C" fn duvm_capacity_total() -> u64 {
    get_pool().map(|p| p.capacity().0).unwrap_or(0)
}

/// Get used capacity in pages.
#[unsafe(no_mangle)]
pub extern "C" fn duvm_capacity_used() -> u64 {
    get_pool().map(|p| p.capacity().1).unwrap_or(0)
}
